FROM node:12 as build-stage
WORKDIR /app
COPY package.json ./
COPY *.js ./
COPY auth_config.json ./
RUN npm install
COPY . .
RUN npm run build

FROM nginx
RUN mkdir /app
COPY --from=build-stage /app/dist /app
COPY ./config/nginx.conf /etc/nginx/nginx.conf
